[package]
name = "matrix_polynomial_analysis"
version = "0.1.0"
authors = ["Ben Clark <thrinador1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.30.1", features = ["rand"] }
